name: "Deploy Frontend to S3"
description: "Builds and deploys the React frontend to AWS S3"
inputs:
  github_token:
    required: true
    description: "The github token"

runs:
  using: "composite"
  steps:

    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: wheels-data

    - run: tar xvf dist.tar.gz
      shell: bash

    - uses: actions/create-release@v1.0.0
      id: create_release
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - uses: svenstaro/upload-release-action@2.2.1
      with:
        repo_token: ${{ github.token }}
        tag_name: ${{ github.ref }}
        file_glob: true
        file: dist/*.whl
    # - name: Create GitHub Release
    #   shell: bash
    #   uses: actions/create-release@v1.0.0
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: ${{ github.ref }}
    #     draft: false
    #     prerelease: false

    # - name: Download a single artifact
    #   uses: actions/download-artifact@v3
    #   with:
    #     name: windows-binary

    # - name: Download a single artifact
    #   uses: actions/download-artifact@v3
    #   with:
    #     name: linux-binary
