name: Build all artifacts
on:
  push:
  workflow_call:

jobs:
  windows:
    uses: ./.github/workflows/windows-build.yaml
  linux:
    uses: ./.github/workflows/linux-build.yaml
  wheels:
    uses: ./.github/workflows/wheels-build.yaml


  build_all:
    runs-on: ubuntu-20.04
    needs: [wheels, linux, windows]
    steps:
      - uses: actions/checkout@v2
      - name: Deploy frontend
        uses: ./.github/actions/github-release

  # notify:
  #   needs: build_all
  #   runs-on: ubuntu-latest
  #   needs: github
  #   steps:
  #     - run: echo all built
