name: Build all artifacts
on:
  push:
  workflow_call:

jobs:
  windows:
    uses: ./.github/workflows/windows-build.yaml
  linux:
    uses: ./.github/workflows/linux-build.yaml
  wheels:
    uses: ./.github/workflows/wheels-build.yaml
  github:
    uses: ./.github/workflows/github-release.yaml

  build_all:
    runs-on: ubuntu-20.04
    needs: [wheels, linux, windows]
    steps:
      - run: done

  notify:
    needs: build_all
    runs-on: ubuntu-latest

    steps:

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-binary

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-binary
