name: Build Linux static binary
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: joaompinto/build-python-static-bin-action@v1
        with:
          python_package: 'stdrun'
