name: Build all artifacts
on:
  push:
  workflow_call:

jobs:
  windows:
    uses: ./.github/workflows/windows-build.yaml
  linux:
    uses: ./.github/workflows/linux-build.yaml
  wheels:
    uses: ./.github/workflows/wheels-build.yaml

  full_release:
    runs-on: ubuntu-20.04
    needs: [wheels, linux, windows]
    steps:

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-binary

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-binary

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
