name: Full release
on:
  push:
  workflow_call:

jobs:
  windows:
    uses: ./.github/workflows/windows-build.yaml
  linux:
    uses: ./.github/workflows/linux-build.yaml
  wheels:
    uses: ./.github/workflows/wheels-build.yaml


  create_github_release:
    runs-on: ubuntu-20.04
    needs: [wheels, linux, windows]
    steps:
      - uses: actions/checkout@v2
      - name: Create GitHub Release
        uses: ./.github/actions/github-release

  create_pypi_release:
    runs-on: ubuntu-20.04
    needs: create_github_release
    steps:
      - uses: actions/checkout@v2
      - name: Create Pypi Release
        uses: ./.github/actions/pypi-release
