name: Regular release
on: push

jobs:
  build-windows:
    runs-on: ubuntu-20.04
    needs: [windows-binary-build]
    steps:
      - run: echo ok

  main: # github requires a non dependent job
    runs-on: ubuntu-20.04
    steps:
      - run: echo ok
