name: Regular release
on: push

jobs:
  windows:
    uses: ./.github/workflows/windows-build.yaml
  linux:
    uses: ./.github/workflows/linux-build.yaml
  wheels:
    uses: ./.github/workflows/wheels-build.yaml

  full_release:
    runs-on: ubuntu-20.04
    needs: [wheels, linux, windows]
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-binary
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-binary
