name: Windows binary build
on:
  workflow_call:
      inputs:
        python_package:
          required: true
            type: string

jobs:
  create_release:
    name: Create Windows binary
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: x64
      - run: pip install Nuitka zstandard
      - run: python -m nuitka --assume-yes-for-downloads --onefile ${{ inputs.python_package }}
