name: Windows Executable (x64)
on: workflow_call

jobs:
  create_exe:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: x64
      - run: pip install ordered-set wheel zstandard Nuitka
      - run: python -m nuitka --assume-yes-for-downloads --follow-imports --onefile ${{ github.event.repository.name }}
      - run: ls -ltr stdrun.build
      - name: Archive the resulting executable
        uses: actions/upload-artifact@v3
        with:
          name: windows-binary
          path: ${{ github.event.repository.name }}.exe
          retention-days: 1
